"""卡牌库存取 + schema 校验（式神项目制）。"""

from .projects import (
    MAX_CARDS,
    MAX_SHIKIGAMI,
    StoreError,
    create_project,
    delete_card,
    delete_mechanism,
    delete_project,
    list_cards,
    list_mechanisms,
    list_projects,
    load_card,
    load_mechanism,
    rename_project,
    save_card,
    save_mechanism,
)
from .schema import (
    CARD_TYPES,
    FACTIONS,
    LEVELS,
    MECH_BADGES,
    MECH_FRAMES,
    RARITIES,
    SchemaError,
    validate_card,
    validate_mechanism,
)

__all__ = [
    "CARD_TYPES",
    "FACTIONS",
    "LEVELS",
    "MAX_CARDS",
    "MAX_SHIKIGAMI",
    "MECH_BADGES",
    "MECH_FRAMES",
    "RARITIES",
    "SchemaError",
    "StoreError",
    "create_project",
    "delete_card",
    "delete_mechanism",
    "delete_project",
    "list_cards",
    "list_mechanisms",
    "list_projects",
    "load_card",
    "load_mechanism",
    "rename_project",
    "save_card",
    "save_mechanism",
    "validate_card",
    "validate_mechanism",
]
